# Generated by Django 5.2.4 on 2025-08-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_paid_user',
            new_name='has_paid',
        ),
    ]
