# Generated by Django 5.2.4 on 2025-08-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_paid_user_profile_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chemistry_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='math_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='physics_level',
            field=models.IntegerField(default=1),
        ),
    ]
