# Generated by Django 5.2.4 on 2025-08-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_chemistry_level_profile_math_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
