# Generated by Django 5.2.4 on 2025-08-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exercise_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
