# Generated by Django 5.2.4 on 2025-08-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exerciserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sub_topic',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
